version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: url_shortener
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root1234
      DB_NAME: url_shortener

volumes:
  mysql_data:
